#!/usr/bin/env python3

import os
import select
from Xlib import display, X

class Tiler:
    def __init__(self):
        self.FIFO_PATH = os.path.expanduser("~/.tiler.sock")
        if os.path.exists(self.FIFO_PATH):
            os.remove(self.FIFO_PATH)
        os.mkfifo(self.FIFO_PATH)
        
        self.dpy = display.Display()
        
    def start(self):
        try:
            self.root = self.dpy.screen().root
            geom = self.root.get_geometry()
            
            self.screen_width, self.screen_height = geom.width, geom.height
            self.half_screen_width = self.screen_width // 2
            self.half_screen_height = self.screen_height // 2
            
            print(f"[tilerd] Listening on {self.FIFO_PATH}...")
            while True:
                with open(self.FIFO_PATH, "r") as fifo:
                    ready, _, _ = select.select([fifo], [], [], 1)
                    if ready:
                        line = fifo.readline().strip()
                        if line:
                            self.handle_action(line)
        except Exception as e:
            print(f"[tilerd] Error: {e}")
        except KeyboardInterrupt:
            print("[tilerd] Shutting down...")
        finally:
            self.dpy.close()
        
    def handle_action(self, action):
        if action not in {'center', 'fullscreen', 'left', 'right', 'up', 'down'}:
            return
        
        active_id = self.get_active_window_id()
        geom = self.get_geometry(active_id)
        self.move_resize(geom["object"], *self.generate_dimensions(geom, action))

    def get_active_window_id(self):
        net_active_window = self.dpy.intern_atom('_NET_ACTIVE_WINDOW')
        window_id = self.root.get_full_property(net_active_window, 0).value[0]
        return window_id

    def move_resize(self, window, x, y, width, height):
        window.configure(x=x, y=y, width=width, height=height)
        self.dpy.sync()
        
    def get_geometry(self, active_id):
        chain = []
        current = self.dpy.create_resource_object('window', active_id)
        active_object = current
        while True:
            info = {
                'id': current.id,
                'name': (current.get_wm_name() or b''),
                'geometry': current.get_geometry()
            }
            parent = current.query_tree().parent
            if not parent:
                break
            chain.append(info)
            current = self.dpy.create_resource_object('window', parent.id)
            
        return {
            "object": active_object,
            "width": chain[0]['geometry'].width,
            "height": chain[0]['geometry'].height,
            "ancestor_x": chain[-1]['geometry'].x,
            "ancestor_y": chain[-1]['geometry'].y,
            "ancestor_width": chain[-1]['geometry'].width,
            "ancestor_height": chain[-1]['geometry'].height,
        }

    def generate_dimensions(self, geom, action):
        overhead_x = geom["ancestor_width"] - geom["width"]
        overhead_y = geom["ancestor_height"] - geom["height"]
        
        full_width = self.screen_width - overhead_x
        full_height = self.screen_height - overhead_y
        half_width = self.half_screen_width - overhead_x
        half_height = self.half_screen_height - overhead_y

        x_new = y_new = w_new = h_new = 0

        if action == 'center':
            w_new, h_new = int(0.75 * self.screen_width), int(0.75 * self.screen_height)
            x_new = (self.screen_width - w_new - overhead_x) // 2
            y_new = (self.screen_height - h_new -overhead_y) // 2

        elif action == 'fullscreen':
            x_new, y_new = 0, 0
            w_new, h_new = full_width, full_height

        elif action in {'left', 'right'}:
            x_new = 0 if action == 'left' else self.half_screen_width
            w_new = half_width
            if geom["width"] <= half_width and geom["ancestor_x"] == x_new and geom["height"] >= half_height or geom["height"] == full_height:
                y_new = 0
                h_new = full_height
            else:
                y_new = 0 if geom["ancestor_y"] < self.half_screen_height else self.half_screen_height
                h_new = half_height

        elif action in {'up', 'down'}:
            y_new = 0 if action == 'up' else self.half_screen_height
            h_new = half_height
            if geom["height"] <= half_height and geom["ancestor_y"] == y_new and geom["width"] >= half_width or geom["width"] == full_width:
                x_new = 0
                w_new = full_width
            else:
                x_new = 0 if geom["ancestor_x"] < self.half_screen_width else self.half_screen_width
                w_new = half_width

        return x_new, y_new, w_new, h_new

if __name__=="__main__":
    tiler = Tiler()
    tiler.start()